src/WebClient/Models/FileDetails.cs
namespace SimpStorage.WebClient.Models
{
    public record FileDetails(
        string Filename,
        string Extension,
        string ContentType,
        byte[] Content
    );
}

src/WebClient/Models/FileLookupItem.cs
using System;

namespace SimpStorage.WebClient.Models
{
    public record FileLookupItem(
        Guid Id,
        string Filename,
        long Size,
        DateTime UploadedAtDate
    )
    {
        private enum SizeUnit
        {
            Byte, KB, MB, GB, TB, PB, EB, ZB, YB
        }

        public string SizeToString()
        {
            var (value, unit) = Convert(0);
            return $"{value.ToString("0.00")} {((SizeUnit)unit).ToString()}";
        }

        private (double, int) Convert(int unit)
        {
            var value = (Size / (double)Math.Pow(1024, (Int64)unit));
            if (value >= 1000)
            {
                return Convert(unit + 1);
            }

            return (value, unit);
        }
    }
}

src/WebClient/Models/UploadFile.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace SimpStorage.WebClient.Models
{
    public record UploadFile(
        string? Filename,
        [Required] IFormFile FileInfo
    );
}

src/WebClient/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SimpStorage.WebClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; } = default!;

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/WebClient/Pages/FileStorage/Components/RenderFileContent/RenderFileContentViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SimpStorage.WebClient.Pages.FileStorage.Components.RenderFileContent
{
    public class RenderFileContentViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string contentType, byte[] content)
        {
            var viewModel = new RenderFileContentViewModel(contentType, content);
            return await Task.FromResult(View(viewModel));
        }
    }
}

src/WebClient/Pages/FileStorage/DetailsPage.cshtml.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpStorage.Application.Queries.GetBinaryObjectDetails;
using SimpStorage.WebClient.Models;

namespace SimpStorage.WebClient.Pages.FileStorage
{
    public class DetailsPageModel : PageModel
    {
        private readonly IMediator _mediator;

        [FromRoute]
        public Guid Id { get; set; }

        public FileDetails Details { get; private set; }
            = default!;

        public DetailsPageModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync()
        {
            var requestQuery = new GetBinaryObjectDetailsQuery(Id);
            var queryResponse = await _mediator.Send(requestQuery, HttpContext.RequestAborted);

            Details = new FileDetails(
                queryResponse.Metadata.Filename,
                queryResponse.Metadata.Extension,
                queryResponse.Metadata.ContentType,
                queryResponse.Data
            );
        }
    }
}

src/WebClient/Pages/FileStorage/IndexPage.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpStorage.Application.Queries.GetBinaryObjectsCollection;
using SimpStorage.WebClient.Models;

namespace SimpStorage.WebClient.Pages.FileStorage
{
    public class IndexPageModel : PageModel
    {
        private readonly IMediator _mediator;

        [FromQuery]
        public string Sort { get; set; }
            = string.Empty;

        public IEnumerable<FileLookupItem> FileCollection { get; private set; }
            = new FileLookupItem[] { };

        public IndexPageModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync()
        {
            var order = GetOrderByQueryPropertySort();
            var requestQuery = new GetBinaryObjectsCollectionQuery(15, 0, order);
            var queryResponse = await _mediator.Send(requestQuery, HttpContext.RequestAborted);
            FileCollection = queryResponse.Select(x =>
                new FileLookupItem(x.Id, x.Metadata.Filename + x.Metadata.Extension, x.Metadata.Size, x.Metadata.CreationDate));
        }

        private BinaryObjectsCollectionOrder GetOrderByQueryPropertySort()
        {
            switch (Sort)
            {
                case "filename":
                    return BinaryObjectsCollectionOrder.ByFilename;

                case "size":
                    return BinaryObjectsCollectionOrder.BySize;

                case "uploaded-at-date":
                    return BinaryObjectsCollectionOrder.ByCreationDate;

                default:
                    return BinaryObjectsCollectionOrder.None;
            }
        }
    }
}

src/WebClient/Pages/FileStorage/UploadPage.cshtml.cs
using System.IO;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpStorage.Application.Commands.AddBinaryObject;
using SimpStorage.WebClient.Models;

namespace SimpStorage.WebClient.Pages.FileStorage
{
    public class UploadPageModel : PageModel
    {
        private readonly IMediator _mediator;

        [BindProperty]
        public UploadFile UploadFile { get; set; } = default!;

        public UploadPageModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            using (var stream = new MemoryStream())
            {
                await UploadFile.FileInfo.CopyToAsync(stream);

                var extension = Path.GetExtension(UploadFile.FileInfo.FileName);
                var filename = string.IsNullOrWhiteSpace(UploadFile.Filename)
                    ? UploadFile.FileInfo.FileName.Replace(extension, string.Empty)
                    : UploadFile.Filename;

                var requestCommand = new AddBinaryObjectCommand(UploadFile.FileInfo.Length, filename,
                    extension, UploadFile.FileInfo.ContentType, stream.GetBuffer());
                await _mediator.Send(requestCommand);
            }

            return await Task.FromResult(RedirectToPage("IndexPage"));
        }
    }
}

src/WebClient/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimpStorage.WebClient.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            return Redirect("/file-storage");
        }
    }
}

src/WebClient/Pages/FileStorage/Components/RenderFileContent/Default.cshtml
@model RenderFileContentViewModel

@switch (Model.FileContentType)
{
    case FileContentType.Image:
        <img src="@Model.ShowAsMediaContent()" class="img-fluid img-thumbnail rounded mx-auto d-block" />
        break;

    case FileContentType.Video:
        <div class="embed-responsive embed-responsive-16by9">
            <video class="embed-responsive-item" preload="metadata" controls loop>
                <source src="@Model.ShowAsMediaContent()" type="@Model.ContentType">
            </video>
        </div>
        break;

    case FileContentType.Unsupported:
    default:
        <h6 class="text-center mt-3">File content not supported to preview</h6>
        break;
}

src/WebClient/Pages/FileStorage/DetailsPage.cshtml
@page "/file-storage/{Id}"
@model DetailsPageModel
@{
    ViewData["Title"] = $"Details {Model.Details.Filename}";
}

<section>
    <h1 class="display-3">@Model.Details.Filename</h1>

    <div class="row">

        <div class="col">
            <table class="table">
                <tbody>

                    <tr class="d-flex">
                        <td class="col-3">Filename</td>
                        <td class="col">@(Model.Details.Filename + Model.Details.Extension)</td>
                    </tr>

                    <tr class="d-flex">
                        <td class="col-3">ContentType</td>
                        <td class="col">@Model.Details.ContentType</td>
                    </tr>

                </tbody>
            </table>
        </div>

        <div class="col-3">
            <div class="btn-group-vertical w-100">
                <a type="button" class="btn btn-secondary" asp-area="" asp-page="IndexPage">Back</a>
            </div>
        </div>

        <div class="col-12">
            @await Component.InvokeAsync("RenderFileContent", new {
            contentType = Model.Details.ContentType,
            content = Model.Details.Content })
        </div>

    </div>
</section>

src/WebClient/Pages/FileStorage/IndexPage.cshtml
@page "/file-storage"
@model IndexPageModel
@{
    ViewData["Title"] = "File storage";
}

@section Scripts {
<script>
    $(document).ready(() => {
        const filesTableRows = document
            .getElementById("files-table")
            .getElementsByTagName("tr");

        const relocateOnClickHandler = (row) => {
            return () => {
                const fileId = row.getElementsByTagName("td")["item-identifier"].innerText;
                const relocateTo = '@Url.Page("DetailsPage", new { Id = "js-item-identifier" })';
                location.href = relocateTo.replace("js-item-identifier", fileId);
            }
        };

        for (const current of filesTableRows) {
            current.onclick = relocateOnClickHandler(current);
        }
    });

</script>
}

<section>
    <div class="row">

        <div class="btn-group col-2 offset-10 p-0" role="group">
            <a type="button" class="btn btn-primary" asp-area="" asp-page="UploadPage">Upload</a>
        </div>

        <table class="table mt-3 col-12" id="files-table">
            <thead class="thead-dark">
                <tr class="d-flex">
                    <th hidden></th>
                    <th class="col">
                        <a class="text-light" href="?sort=filename">Filename</a>
                        @if (Model.Sort == "filename")
                        {
                            <small><span class="oi oi-arrow-bottom"></span></small>
                        }
                    </th>
                    <th class="col-2">
                        <a class="text-light" href="?sort=size">Size</a>
                        @if (Model.Sort == "size")
                        {
                            <small><span class="oi oi-arrow-bottom"></span></small>
                        }
                    </th>
                    <th class="col-2">
                        <a class="text-light" href="?sort=uploaded-at-date">Uploaded at</a>
                        @if (Model.Sort == "uploaded-at-date")
                        {
                            <small><span class="oi oi-arrow-bottom"></span></small>
                        }
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.FileCollection.Count() == 0)
                {
                    <tr class="d-flex">
                        <th class="col" scope="3">No files uploaded yet</th>
                    </tr>
                }
                @foreach (var item in Model.FileCollection)
                {
                    <tr class="d-flex">
                        <td id="item-identifier" hidden>@item.Id</td>
                        <td class="col">@item.Filename</td>
                        <td class="col-2">@item.SizeToString()</td>
                        <td class="col-2">@item.UploadedAtDate.ToLocalTime().ToString("d")
                            @item.UploadedAtDate.ToLocalTime().ToString("t")
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</section>

src/WebClient/Pages/FileStorage/UploadPage.cshtml
@page "/file-storage/upload"
@model UploadPageModel
@{
    ViewData["Title"] = "Upload new file";
}

<section>
    <div class="row">

        <form class="col-8 offset-2" method="post" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly"></div>

            <div class="form-group">
                <label for="filenameControl">Filename :</label>
                <input type="text" class="form-control" asp-for="UploadFile.Filename" id="filenameControl"
                    placeholder="New filename">
                <span class="text-danger" asp-validation-for="UploadFile.Filename"></span>
            </div>

            <div class="form-group">
                <label for="uploadControl">File :</label>
                <input type="file" class="form-control-file" asp-for="UploadFile.FileInfo" id="uploadControl">
                <span class="text-danger" asp-validation-for="UploadFile.FileInfo"></span>
            </div>

            <div class="btn-group d-flex">
                <a type="button" class="btn btn-secondary col-2 offset-8" asp-area="" asp-page="IndexPage">Back</a>
                <button type="submit" class="btn btn-success col-2">Upload</button>
            </div>
        </form>

    </div>
</section>

src/WebClient/Pages/Index.cshtml
@page
@model IndexModel
@{
}

src/WebClient/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpStorage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.0/font/css/open-iconic-bootstrap.min.css"
        integrity="sha512-UyNhw5RNpQaCai2EdC+Js0QL4RlVmiq41DkmCJsRV3ZxipG2L0HhTqIf/H9Hp8ez2EnFlkBnjRGJU2stW3Lj+w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SimpStorage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SimpStorage
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>